apiVersion: v1
kind: Pod
metadata:
  name: first-pod
spec:
  containers:
    - name: first-container
      image: us-central1-docker.pkg.dev/load-balancer-452617/k8/hello-docker-k8s
      ports:
        - containerPort: 5000